### ISSUE TITLE
ERROR: Module "NoMoreTitles"

### ISSUE THREAD

**Issue by 1StarDuster** [SaltyMonkey/NoMoreAnnoyingTitles#4]
Good Evening Salty!
I am new and am not sure how to fix this in my tool box, or maybe it just needs to be updated. Below are showing RED errors when I use the toolbox. Everything else is fine except this. I was hoping you could help advise me with the next steps.
Do I just wait for update, or do I need to disable? 
Thank you so much for all you do, I am grateful and really appreciate your hard work.
Thanks again, AZStarDuster  Priest Lvl 70 Kaia Gear 10
See Below error from toolbox after launch
::::::::::::::::

18:26:49.748] [mods] ERROR: Module "NoMoreTitles" (no-more-annoying-titles) could not be applied to server connection!
[18:26:49.748] [mods] ERROR: Please contact the module's author: https://github.com/SaltyMonkey/NoMoreAnnoyingTitles/issues
[18:26:49.749] Error: [dispatch] [no-more-annoying-titles] hook: Error: version 15 of message (name: "S_SPAWN_USER", code: 37833) is outdated and cannot be used anymore
    at Dispatch.createHook (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod.js:280:36)
    at new NoMoreAnnoyingTitles (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\mods\no-more-annoying-titles\index.js:27:6)
    at new <anonymous> (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod-legacy-wrapper.js:145:13)
    at Mod.loadNetworkInstance (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\Users\azsta\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:231:25)

**Comment by SaltyMonkey** [comment]
i will update it at weekend. Thx

**Comment by 1StarDuster** [comment]
kk
😊
Happy Holidays!

**Comment by 1StarDuster** [comment]
Hi Salty!

This weekend coming? 12/5?
Just because I looked and it didn't change unless you fixed it after I
looked and checked. I had to shut it off so NOTITLES would not display red
error.
Thank you Salty for all you do.
I really mean that.
-AZStarDuster (-kt)
Star.Priestess level 70 Priest
🎄
